name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Next.js App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with NPM cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' 

      - name: Clean up node_modules (keep lockfile!)
        run: rm -rf node_modules

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: NODE_OPTIONS=--openssl-legacy-provider npm run build
